# Generated by Django 5.1.2 on 2024-10-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
